### ISSUE TITLE
Duplicated Cod

### ISSUE THREAD

**Issue by GitAlison** [felipemaion/financial-management-gate-django#3]
https://github.com/felipemaion/financial-management-gate-django/blob/b4d1d9b1179ee0308f93628847b70894069d802a/backend/instrument/models.py#L24
class BaseTimeModel(models.Model):
    created_at = models.DateTimeField(
        "Created at", auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(
        "Updated at", auto_now=True, blank=True)

    class Meta:
        abstract = True

pra evitar a duplicidade coloca isso lá no app core que voce criou 

e quando vc instanciar BaseTimeModel em qualquer outro model esses 2 campos já serao alto atribuidos

**Comment by felipemaion** [comment]
Fixed!
